projectId=finn-tid-bryllaup
secretManagerProjectId=${projectId}
quarkus.rest-client."no.mads.Klient".url = https://api.booking.oslo.kommune.no/api/schedule

quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${sm//projects/finn-tid-bryllaup/secrets/epostbrukernavn}
%dev.quarkus.mailer.from=${quarkus.epostbrukernavn}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${sm//projects/finn-tid-bryllaup/secrets/epostbrukernavn}
%dev.quarkus.mailer.username=${quarkus.epostbrukernavn}
quarkus.mailer.password=${sm//projects/finn-tid-bryllaup/secrets/epostpassord}
%dev.quarkus.mailer.password=${quarkus.epostpassord}

quarkus.mailer.mock=false