projectId=finn-tid-bryllaup
secretManagerProjectId=${projectId}
quarkus.rest-client."no.mads.Klient".url = https://api.booking.oslo.kommune.no/api/schedule

quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${quarkus.epost}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${quarkus.epost}
quarkus.mailer.password=${quarkus.epostpassord}

quarkus.mailer.mock=false # In dev mode, prevent from using the mock SMTP server